Adjusting repo for CLI (GIM-114)
ghga-de/ghga-transpiler pull request #2
Opened 2023-05-11 11:33 UTC by sbilge

- API-related files are deleted

2023-05-12 15:05 UTC, lkuchenb requested changes

2023-05-12 15:05 UTC, lkuchenb commented on ghga_transpiler/config.py
> +class Config(ApiConfigBase, extra=Extra.allow):  # type: ignore
Is this needed for this PR?

2023-05-12 15:05 UTC, lkuchenb commented on .devcontainer/docker-compose.yml
environment of the app service and other services should be removed

2023-05-16 17:00 UTC, sbilge commented on .devcontainer/docker-compose.yml
Should I also remove ghga_transpiler_CONFIG_YAML env?

2023-05-23 10:25 UTC, lkuchenb commented on .devcontainer/docker-compose.yml
Yes, and please also remove all config related checks (which currently make CI fail)

2023-05-23 10:26 UTC, lkuchenb requested changes
See above, please remove the remaining config components

2023-05-24 12:27 UTC, lkuchenb approved these changes

2023-05-24 12:29 UTC, merged