Template update
ghga-de/ghga-transpiler pull request #25
Opened 2023-10-23 14:27 UTC by sbilge

Updated service template

2023-10-23 14:31 UTC, sbilge commented
I cannot find why the Tests check fails to find the module "openpyxl". Any pointers? @lkuchenb

2023-10-23 19:02 UTC, lkuchenb commented
You didn't run `./scripts/update_lock.py` after changing the `pyproject.toml` file.

2023-10-23 19:03 UTC, lkuchenb commented on pyproject.toml
> +    "PyYAML==6.0"
We don't have to pin these to exact versions anymore, pinning major should be fine.

2023-10-24 12:13 UTC, lkuchenb requested changes

2023-10-24 12:13 UTC, lkuchenb commented on pyproject.toml
> +    "PyYAML==6.0"
```suggestion
    "openpyxl >= 3.1.2, == 3.*",
    "defusedxml ~= 0.7.1",
    "PyYAML == 6.*"
```

2023-10-25 19:17 UTC, lkuchenb approved these changes

2023-10-27 07:51 UTC, merged