updated outdated dependencies and related
ghga-de/ghga-transpiler pull request #31
Opened 2023-11-03 15:39 UTC by dontseyit

This PR updates the outdated GHGA dependencies and includes minor code changes required by the Pydantic version upgrade.

2023-11-06 10:19 UTC, lkuchenb requested changes

2023-11-06 10:19 UTC, lkuchenb commented on pyproject.toml
> +    "hexkit[akafka,s3,mongodb] >= 0.11.1",
```suggestion
    "typer ~= 0.9.0",
    "ghga-service-commons[api] >= 1.1.0, <2",
    "ghga-event-schemas >= 1.0.0, <2",
    "hexkit[akafka,s3,mongodb] ~= 0.11.1",
```
This should now comply with draft SOP012 for a non-service library, right?

2023-11-07 10:17 UTC, lkuchenb approved these changes

2023-11-07 12:19 UTC, merged

2023-11-07 12:26 UTC, sbilge approved these changes